spring:
  datasource:
    url: 'jdbc:postgresql:${DB_NAME:torneios}'
    username: ${DB_USER:utorneio}
    password: ${DB_PASSWORD:torneios@ufg}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
