spring:
  datasource:
    url: 'jdbc:postgresql:${DB_NAME:torneios}'
    username: ${DB_USER:utorneio}
    password: ${DB_PASSWORD:torneios@ufg}
    driver-class-name: org.postgresql.Driver
  jersey.application-path: /api
