/**
 * Api Torneio Application Documentation
 * \"Spring Boot REST API for manage torneios\"
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpEvent, HttpHeaders, HttpResponse} from '@angular/common/http';

import {Observable} from 'rxjs/Observable';

import {TorneiosDTO} from '../model/torneiosDTO';

import {BASE_PATH} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class TorneioControllerService {

  protected basePath = 'http://localhost:9090';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }


  /**
   * getTorneio
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTorneioUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<TorneiosDTO>;
  public getTorneioUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TorneiosDTO>>;
  public getTorneioUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TorneiosDTO>>;
  public getTorneioUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getTorneioUsingGET.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/xml',
      'application/fixedposition',
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<TorneiosDTO>(`${this.basePath}/torneio/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * getTorneios
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTorneiosUsingGET(observe?: 'body', reportProgress?: boolean): Observable<TorneiosDTO>;
  public getTorneiosUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TorneiosDTO>>;
  public getTorneiosUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TorneiosDTO>>;
  public getTorneiosUsingGET(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/xml',
      'application/fixedposition',
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get<TorneiosDTO>(`${this.basePath}/torneio`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * saveTorneios
   *
   * @param torneiosDTO torneiosDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public saveTorneiosUsingPOST(torneiosDTO: TorneiosDTO, observe?: 'body', reportProgress?: boolean): Observable<TorneiosDTO>;
  public saveTorneiosUsingPOST(torneiosDTO: TorneiosDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TorneiosDTO>>;
  public saveTorneiosUsingPOST(torneiosDTO: TorneiosDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TorneiosDTO>>;
  public saveTorneiosUsingPOST(torneiosDTO: TorneiosDTO, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    if (torneiosDTO === null || torneiosDTO === undefined) {
      throw new Error('Required parameter torneiosDTO was null or undefined when calling saveTorneiosUsingPOST.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/xml',
      'application/fixedposition',
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post<TorneiosDTO>(`${this.basePath}/torneio`,
      torneiosDTO,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

}
