/**
 * Api Torneio Application Documentation
 * \"Spring Boot REST API for manage torneios\"
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TorneioDTO {
  city?: string;
  country?: string;
  date?: string;
  description?: string;
  state?: string;
}
